name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Training-Room-Booking-VINSYS/backend || git clone https://github.com/zargon01/Training-Room-Booking-VINSYS.git && cd Training-Room-Booking-VINSYS/backend
            git pull origin main
            npm install
            pm2 restart vinsys-backend || pm2 start server.js --name vinsys-backend
            pm2 save
